### ISSUE TITLE
Example isn't compiles

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/experimental.xml#14]
_From @denizzzka on December 14, 2016 13:19_

First example from https://lodo1995.github.io/experimental.xml/std/experimental/xml.html returns
```
source/map.d(25,13): Error: no property 'lexer' for type 'string'
```

_Copied from original issue: lodo1995/experimental.xml#38_

**Comment by wilzbach** [comment]
_From @WebFreak001 on June 22, 2017 7:28_

bump - maybe release a new version?

**Comment by wilzbach** [comment]
_From @WebFreak001 on June 22, 2017 11:36_

Well you could try out the example on the latest release: https://github.com/lodo1995/experimental.xml/blob/255caeaf4231fb66f4c81d23cd37814670ac2306/source/std/experimental/xml/package.d#L35

**Comment by wilzbach** [comment]
Works with by #20 which tagged as v0.1.5
Feel free to submit a PR that converts the ddoc examples to real ddoc-ed module-level unittests, s.t. such things can't happen.
